name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *' # every day at 00:00
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Check all links
      run: npx markdown-link-check --config .github/workflows/config.json README.md
    - name: "Check for exactly 200 links"
      run: |
        if [ $(grep "\- \[" README.md | grep -Eo "https?://[^][ ]+" | uniq | wc -l) != 200 ]; then
          echo "ERROR: List is not exactly 200 entries"
          exit 1
        fi
