name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *' # every day at 00:00
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/config.json'
  two-hundred-links-check:
    runs-on: ubuntu-latest
    steps:
    - name: "check list length"
      run: |
        if [ $(grep "\- \[" README.md | grep -Eo "https?://[^][ ]+" | uniq | wc -l) != 200 ]; then
          echo "ERROR: List is not exactly 200 entries"
          exit 1
        fi
